### ISSUE TITLE
Overload "bool" for "is_success"

### ISSUE THREAD

**Issue by preaction** [rjbs/Process-Status#3]
I'd like to encapsulate the output of a method that runs an external command in such a way that one could do:

```perl
$status = $cmd->run( ... ) or die q{Could not run command "mycommand": } . $status->as_string;
```

I'll have to overload `bool` to call `is_success` and likely `""` to do something useful like `as_string`.

If you're amenable to this, I can provide a patch.

**Comment by rjbs** [comment]
I would rather not.

Already this works:

```perl
$status = $cmd->run( ... );
$status->assert_ok("mycomand");
```
