### ISSUE TITLE
Add slots for stdout/stderr

### ISSUE THREAD

**Issue by preaction** [rjbs/Process-Status#4]
I'd like to encapsulate the output of a method that runs an external command in such a way that one could do:

```perl
# $output is a Process::Status object
$output = $cmd->run( ... ) or die q{Could not run command "mycommand": } . $output->as_string . "\nSTDOUT: " . $output->stdout . "\nSTDERR: " . $output->stderr;
```

I was considering System::Command, but too much in there involves the running of the actual command.

If you approve, I can provide a patch. If this isn't appropriate for this module, I can build a subclass (Process::Output) or if you have a suggestion, I'm open to it.

**Comment by rjbs** [comment]
I don't think this is an appropriate task for Process::Status, which is really just sugar on top of `$?`.  I'd suggest making a class that as a `->status` method that returns a Process::Status, plus whatever else you need.
